In [18]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [19]:
#create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [20]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [21]:
#create an instance of OneHotEncoder
encoder= OneHotEncoder()

In [22]:
#perform fit and transform
encoded= encoder.fit_transform(df[['color']]).toarray()

In [23]:
import pandas as pd
encoder_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [24]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [25]:
#new color within red, green, blue
encoder.transform([['blue']]).toarray()

C:\Users\harsh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [26]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [37]:
import seaborn as sns
import pandas as pd
df= sns.load_dataset('tips')

In [39]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [43]:
df[['sex','smoker','day']]

        sex smoker   day
0    Female     No   Sun
1      Male     No   Sun
2      Male     No   Sun
3      Male     No   Sun
4    Female     No   Sun
..      ...    ...   ...
239    Male     No   Sat
240  Female    Yes   Sat
241    Male    Yes   Sat
242    Male     No   Sat
243  Female     No  Thur

[244 rows x 3 columns]

In [46]:
encoder=OneHotEncoder()

In [48]:
encoded = encoder.fit_transform(df[['sex']]).toarray()

In [55]:
encoded_df= pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [56]:
encoded_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]